name: Test Suite

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php-versions: ['8.0', '8.1']
    name: PHP ${{ matrix.php-versions }} Test
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: dom, mbstring
    - name: Check PHP Version
      run: php -v
    - name: Install composer
      run: cd $GITHUB_WORKSPACE && composer install
    - name: Run tests
      run: cd $GITHUB_WORKSPACE && composer run test